dotenv: .env
dependencies:
  #- <organisation/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
   remappings:
    - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

networks:
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1FA494EC906CE90E9F37563A8AF630E'
    verify: True
  mainet-fork-dev:
    eth_usd_price_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
    verify: False
  development:
    verify: False